services:
  app:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    dns:
      - 8.8.8.8
    command: sh -c "npm install && npm run dev"